// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAccelXChange();
void onAccelYChange();
void onAccelZChange();
void onAlarmTriggeredChange();

float accelX;
float accelY;
float accelZ;
bool alarmTriggered;

void initProperties(){

  ArduinoCloud.addProperty(accelX, READWRITE, ON_CHANGE, onAccelXChange);
  ArduinoCloud.addProperty(accelY, READWRITE, ON_CHANGE, onAccelYChange);
  ArduinoCloud.addProperty(accelZ, READWRITE, ON_CHANGE, onAccelZChange);
  ArduinoCloud.addProperty(alarmTriggered, READWRITE, ON_CHANGE, onAlarmTriggeredChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
